//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wineyes.Search {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Patient : Wineyes.Search.Auditable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PatientsBirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientBirthDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> PatientsBirthDate {
            get {
                return this.PatientsBirthDateField;
            }
            set {
                if ((this.PatientsBirthDateField.Equals(value) != true)) {
                    this.PatientsBirthDateField = value;
                    this.RaisePropertyChanged("PatientsBirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PatientsSex {
            get {
                return this.PatientsSexField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsSexField, value) != true)) {
                    this.PatientsSexField = value;
                    this.RaisePropertyChanged("PatientsSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PatientBirthDateString {
            get {
                return this.PatientBirthDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientBirthDateStringField, value) != true)) {
                    this.PatientBirthDateStringField = value;
                    this.RaisePropertyChanged("PatientBirthDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditable", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wineyes.Search.Study))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wineyes.Search.Image))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wineyes.Search.Patient))]
    public partial class Auditable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Study", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Study : Wineyes.Search.Auditable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StudyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PatientsAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyTimeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsBirthDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PatientsBirthDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Device {
            get {
                return this.DeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceField, value) != true)) {
                    this.DeviceField = value;
                    this.RaisePropertyChanged("Device");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StudyDate {
            get {
                return this.StudyDateField;
            }
            set {
                if ((this.StudyDateField.Equals(value) != true)) {
                    this.StudyDateField = value;
                    this.RaisePropertyChanged("StudyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string StudyId {
            get {
                return this.StudyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyIdField, value) != true)) {
                    this.StudyIdField = value;
                    this.RaisePropertyChanged("StudyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string AccessionNumber {
            get {
                return this.AccessionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessionNumberField, value) != true)) {
                    this.AccessionNumberField = value;
                    this.RaisePropertyChanged("AccessionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> PatientsAge {
            get {
                return this.PatientsAgeField;
            }
            set {
                if ((this.PatientsAgeField.Equals(value) != true)) {
                    this.PatientsAgeField = value;
                    this.RaisePropertyChanged("PatientsAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string StudyDateString {
            get {
                return this.StudyDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyDateStringField, value) != true)) {
                    this.StudyDateStringField = value;
                    this.RaisePropertyChanged("StudyDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string StudyTimeString {
            get {
                return this.StudyTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyTimeStringField, value) != true)) {
                    this.StudyTimeStringField = value;
                    this.RaisePropertyChanged("StudyTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string PatientsFirstName {
            get {
                return this.PatientsFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsFirstNameField, value) != true)) {
                    this.PatientsFirstNameField = value;
                    this.RaisePropertyChanged("PatientsFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PatientsLastName {
            get {
                return this.PatientsLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsLastNameField, value) != true)) {
                    this.PatientsLastNameField = value;
                    this.RaisePropertyChanged("PatientsLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string PatientsBirthDateString {
            get {
                return this.PatientsBirthDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsBirthDateStringField, value) != true)) {
                    this.PatientsBirthDateStringField = value;
                    this.RaisePropertyChanged("PatientsBirthDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string PatientsSex {
            get {
                return this.PatientsSexField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsSexField, value) != true)) {
                    this.PatientsSexField = value;
                    this.RaisePropertyChanged("PatientsSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime PatientsBirthDate {
            get {
                return this.PatientsBirthDateField;
            }
            set {
                if ((this.PatientsBirthDateField.Equals(value) != true)) {
                    this.PatientsBirthDateField = value;
                    this.RaisePropertyChanged("PatientsBirthDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Image", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Image : Wineyes.Search.Auditable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LateralityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MovieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageTimeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsBirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientsSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyTimeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StudyDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SeriesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> InstanceNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Laterality {
            get {
                return this.LateralityField;
            }
            set {
                if ((object.ReferenceEquals(this.LateralityField, value) != true)) {
                    this.LateralityField = value;
                    this.RaisePropertyChanged("Laterality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Root {
            get {
                return this.RootField;
            }
            set {
                if ((object.ReferenceEquals(this.RootField, value) != true)) {
                    this.RootField = value;
                    this.RaisePropertyChanged("Root");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Thumbnail {
            get {
                return this.ThumbnailField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailField, value) != true)) {
                    this.ThumbnailField = value;
                    this.RaisePropertyChanged("Thumbnail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIdField, value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool Movie {
            get {
                return this.MovieField;
            }
            set {
                if ((this.MovieField.Equals(value) != true)) {
                    this.MovieField = value;
                    this.RaisePropertyChanged("Movie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ImageDateString {
            get {
                return this.ImageDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDateStringField, value) != true)) {
                    this.ImageDateStringField = value;
                    this.RaisePropertyChanged("ImageDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ImageTimeString {
            get {
                return this.ImageTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageTimeStringField, value) != true)) {
                    this.ImageTimeStringField = value;
                    this.RaisePropertyChanged("ImageTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string PatientsFirstName {
            get {
                return this.PatientsFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsFirstNameField, value) != true)) {
                    this.PatientsFirstNameField = value;
                    this.RaisePropertyChanged("PatientsFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PatientsLastName {
            get {
                return this.PatientsLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsLastNameField, value) != true)) {
                    this.PatientsLastNameField = value;
                    this.RaisePropertyChanged("PatientsLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string PatientsBirthDate {
            get {
                return this.PatientsBirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsBirthDateField, value) != true)) {
                    this.PatientsBirthDateField = value;
                    this.RaisePropertyChanged("PatientsBirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string PatientsSex {
            get {
                return this.PatientsSexField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientsSexField, value) != true)) {
                    this.PatientsSexField = value;
                    this.RaisePropertyChanged("PatientsSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdField, value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string StudyId {
            get {
                return this.StudyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyIdField, value) != true)) {
                    this.StudyIdField = value;
                    this.RaisePropertyChanged("StudyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string AccessionNumber {
            get {
                return this.AccessionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessionNumberField, value) != true)) {
                    this.AccessionNumberField = value;
                    this.RaisePropertyChanged("AccessionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string StudyDateString {
            get {
                return this.StudyDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyDateStringField, value) != true)) {
                    this.StudyDateStringField = value;
                    this.RaisePropertyChanged("StudyDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string StudyTimeString {
            get {
                return this.StudyTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyTimeStringField, value) != true)) {
                    this.StudyTimeStringField = value;
                    this.RaisePropertyChanged("StudyTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.DateTime StudyDateTime {
            get {
                return this.StudyDateTimeField;
            }
            set {
                if ((this.StudyDateTimeField.Equals(value) != true)) {
                    this.StudyDateTimeField = value;
                    this.RaisePropertyChanged("StudyDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<int> SeriesNumber {
            get {
                return this.SeriesNumberField;
            }
            set {
                if ((this.SeriesNumberField.Equals(value) != true)) {
                    this.SeriesNumberField = value;
                    this.RaisePropertyChanged("SeriesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<int> InstanceNumber {
            get {
                return this.InstanceNumberField;
            }
            set {
                if ((this.InstanceNumberField.Equals(value) != true)) {
                    this.InstanceNumberField = value;
                    this.RaisePropertyChanged("InstanceNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class InvalidParameterException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter {
            get {
                return this.ParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterField, value) != true)) {
                    this.ParameterField = value;
                    this.RaisePropertyChanged("Parameter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class UnconfiguredWebServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Refraction", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Refraction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> SphericalLensPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> CylinderLensPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CylinderAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> CornealVertexDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wineyes.Search.Laterality LateralityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> SphericalLensPower {
            get {
                return this.SphericalLensPowerField;
            }
            set {
                if ((this.SphericalLensPowerField.Equals(value) != true)) {
                    this.SphericalLensPowerField = value;
                    this.RaisePropertyChanged("SphericalLensPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<float> CylinderLensPower {
            get {
                return this.CylinderLensPowerField;
            }
            set {
                if ((this.CylinderLensPowerField.Equals(value) != true)) {
                    this.CylinderLensPowerField = value;
                    this.RaisePropertyChanged("CylinderLensPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> CylinderAxis {
            get {
                return this.CylinderAxisField;
            }
            set {
                if ((this.CylinderAxisField.Equals(value) != true)) {
                    this.CylinderAxisField = value;
                    this.RaisePropertyChanged("CylinderAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<float> CornealVertexDistance {
            get {
                return this.CornealVertexDistanceField;
            }
            set {
                if ((this.CornealVertexDistanceField.Equals(value) != true)) {
                    this.CornealVertexDistanceField = value;
                    this.RaisePropertyChanged("CornealVertexDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Wineyes.Search.Laterality Laterality {
            get {
                return this.LateralityField;
            }
            set {
                if ((this.LateralityField.Equals(value) != true)) {
                    this.LateralityField = value;
                    this.RaisePropertyChanged("Laterality");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Laterality", Namespace="http://schemas.datacontract.org/2004/07/Base")]
    public enum Laterality : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OD = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OS = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTimeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Root {
            get {
                return this.RootField;
            }
            set {
                if ((object.ReferenceEquals(this.RootField, value) != true)) {
                    this.RootField = value;
                    this.RaisePropertyChanged("Root");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Thumbnail {
            get {
                return this.ThumbnailField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailField, value) != true)) {
                    this.ThumbnailField = value;
                    this.RaisePropertyChanged("Thumbnail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ReportId {
            get {
                return this.ReportIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIdField, value) != true)) {
                    this.ReportIdField = value;
                    this.RaisePropertyChanged("ReportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ReportDateString {
            get {
                return this.ReportDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportDateStringField, value) != true)) {
                    this.ReportDateStringField = value;
                    this.RaisePropertyChanged("ReportDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ReportTimeString {
            get {
                return this.ReportTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTimeStringField, value) != true)) {
                    this.ReportTimeStringField = value;
                    this.RaisePropertyChanged("ReportTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string StudyId {
            get {
                return this.StudyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyIdField, value) != true)) {
                    this.StudyIdField = value;
                    this.RaisePropertyChanged("StudyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meridian", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class Meridian : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float K1ValmmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort K1AxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float K2ValmmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort K2AxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float K1ValDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float K2ValDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AvgValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort CylAxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float K1Valmm {
            get {
                return this.K1ValmmField;
            }
            set {
                if ((this.K1ValmmField.Equals(value) != true)) {
                    this.K1ValmmField = value;
                    this.RaisePropertyChanged("K1Valmm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ushort K1Ax {
            get {
                return this.K1AxField;
            }
            set {
                if ((this.K1AxField.Equals(value) != true)) {
                    this.K1AxField = value;
                    this.RaisePropertyChanged("K1Ax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float K2Valmm {
            get {
                return this.K2ValmmField;
            }
            set {
                if ((this.K2ValmmField.Equals(value) != true)) {
                    this.K2ValmmField = value;
                    this.RaisePropertyChanged("K2Valmm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ushort K2Ax {
            get {
                return this.K2AxField;
            }
            set {
                if ((this.K2AxField.Equals(value) != true)) {
                    this.K2AxField = value;
                    this.RaisePropertyChanged("K2Ax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float K1ValD {
            get {
                return this.K1ValDField;
            }
            set {
                if ((this.K1ValDField.Equals(value) != true)) {
                    this.K1ValDField = value;
                    this.RaisePropertyChanged("K1ValD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float K2ValD {
            get {
                return this.K2ValDField;
            }
            set {
                if ((this.K2ValDField.Equals(value) != true)) {
                    this.K2ValDField = value;
                    this.RaisePropertyChanged("K2ValD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public float AvgVal {
            get {
                return this.AvgValField;
            }
            set {
                if ((this.AvgValField.Equals(value) != true)) {
                    this.AvgValField = value;
                    this.RaisePropertyChanged("AvgVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public ushort CylAx {
            get {
                return this.CylAxField;
            }
            set {
                if ((this.CylAxField.Equals(value) != true)) {
                    this.CylAxField = value;
                    this.RaisePropertyChanged("CylAx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class InvalidDeviceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeripheralDegreesModule", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class PeripheralDegreesModule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wineyes.Search.PeripheralDegree[] AsphericitymmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wineyes.Search.PeripheralDegree[] AsphericitydegreesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wineyes.Search.PeripheralDegree[] SagittalRadiusmmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wineyes.Search.PeripheralDegree[] SagittalRadiusdegreesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wineyes.Search.PeripheralDegree[] Asphericitymm {
            get {
                return this.AsphericitymmField;
            }
            set {
                if ((object.ReferenceEquals(this.AsphericitymmField, value) != true)) {
                    this.AsphericitymmField = value;
                    this.RaisePropertyChanged("Asphericitymm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Wineyes.Search.PeripheralDegree[] Asphericitydegrees {
            get {
                return this.AsphericitydegreesField;
            }
            set {
                if ((object.ReferenceEquals(this.AsphericitydegreesField, value) != true)) {
                    this.AsphericitydegreesField = value;
                    this.RaisePropertyChanged("Asphericitydegrees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Wineyes.Search.PeripheralDegree[] SagittalRadiusmm {
            get {
                return this.SagittalRadiusmmField;
            }
            set {
                if ((object.ReferenceEquals(this.SagittalRadiusmmField, value) != true)) {
                    this.SagittalRadiusmmField = value;
                    this.RaisePropertyChanged("SagittalRadiusmm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wineyes.Search.PeripheralDegree[] SagittalRadiusdegrees {
            get {
                return this.SagittalRadiusdegreesField;
            }
            set {
                if ((object.ReferenceEquals(this.SagittalRadiusdegreesField, value) != true)) {
                    this.SagittalRadiusdegreesField = value;
                    this.RaisePropertyChanged("SagittalRadiusdegrees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeripheralDegree", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
    [System.SerializableAttribute()]
    public partial class PeripheralDegree : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SagittalAngleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PeripheralRingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float NasalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TemporalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float InferiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SuperiorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SagittalAngle {
            get {
                return this.SagittalAngleField;
            }
            set {
                if ((this.SagittalAngleField.Equals(value) != true)) {
                    this.SagittalAngleField = value;
                    this.RaisePropertyChanged("SagittalAngle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> PeripheralRing {
            get {
                return this.PeripheralRingField;
            }
            set {
                if ((this.PeripheralRingField.Equals(value) != true)) {
                    this.PeripheralRingField = value;
                    this.RaisePropertyChanged("PeripheralRing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float Nasal {
            get {
                return this.NasalField;
            }
            set {
                if ((this.NasalField.Equals(value) != true)) {
                    this.NasalField = value;
                    this.RaisePropertyChanged("Nasal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float Temporal {
            get {
                return this.TemporalField;
            }
            set {
                if ((this.TemporalField.Equals(value) != true)) {
                    this.TemporalField = value;
                    this.RaisePropertyChanged("Temporal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float Inferior {
            get {
                return this.InferiorField;
            }
            set {
                if ((this.InferiorField.Equals(value) != true)) {
                    this.InferiorField = value;
                    this.RaisePropertyChanged("Inferior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float Superior {
            get {
                return this.SuperiorField;
            }
            set {
                if ((this.SuperiorField.Equals(value) != true)) {
                    this.SuperiorField = value;
                    this.RaisePropertyChanged("Superior");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-csoitalia-it:psearchsvc-v10", ConfigurationName="Search.IPSearchSvc")]
    public interface IPSearchSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatients", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientsInvalidParameterE" +
            "xceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientsUnconfiguredWebSe" +
            "rviceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Patient[] FindPatients(int Maximum, int Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchPatients", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchPatientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchPatientsInvalidParamete" +
            "rExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchPatientsUnconfiguredWeb" +
            "ServiceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Patient[] SearchPatients(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatient", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientUnconfiguredWebSer" +
            "viceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindPatientInvalidParameterEx" +
            "ceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Patient FindPatient(string PatientId, string IdIssuer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudies", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudiesUnconfiguredWebSer" +
            "viceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudiesInvalidParameterEx" +
            "ceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Study[] FindStudies(string PatientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudies", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesUnconfiguredWebS" +
            "erviceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesInvalidParameter" +
            "ExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Study[] SearchStudies(int Maximum, int Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesByDate", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesByDateInvalidPar" +
            "ameterExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchStudiesByDateUnconfigur" +
            "edWebServiceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Study[] SearchStudiesByDate(System.Nullable<System.DateTime> From, System.Nullable<System.DateTime> To, string Device);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudy", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyInvalidParameterExce" +
            "ptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyUnconfiguredWebServi" +
            "ceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Study FindStudy(string StudyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyByAccessionNumber", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyByAccessionNumberRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyByAccessionNumberUnc" +
            "onfiguredWebServiceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindStudyByAccessionNumberInv" +
            "alidParameterExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Study FindStudyByAccessionNumber(string AccessionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindImages", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindImagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindImagesUnconfiguredWebServ" +
            "iceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindImagesInvalidParameterExc" +
            "eptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Image[] FindImages(string StudyId, string Laterality);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetThumbnail", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetThumbnailResponse")]
        System.Drawing.Bitmap GetThumbnail(string Root);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetThumb", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetThumbResponse")]
        System.IO.Stream GetThumb(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindRefractions", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindRefractionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindRefractionsInvalidParamet" +
            "erExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindRefractionsUnconfiguredWe" +
            "bServiceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Refraction[] FindRefractions(string StudyId, string Laterality);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchReports", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchReportsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchReportsInvalidParameter" +
            "ExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/SearchReportsUnconfiguredWebS" +
            "erviceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Report[] SearchReports(string StudyId, string Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindSimK", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindSimKResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindSimKUnconfiguredWebServic" +
            "eExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/FindSimKInvalidParameterExcep" +
            "tionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Meridian[] FindSimK(string StudyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetSimK", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetSimKResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetSimKUnconfiguredWebService" +
            "ExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidDeviceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetSimKInvalidDeviceException" +
            "Fault", Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetSimKInvalidParameterExcept" +
            "ionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.Meridian GetSimK(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetAngle", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetAngleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetAngleUnconfiguredWebServic" +
            "eExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetAngleInvalidParameterExcep" +
            "tionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidDeviceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetAngleInvalidDeviceExceptio" +
            "nFault", Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        int GetAngle(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetBCS", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetBCSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidDeviceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetBCSInvalidDeviceExceptionF" +
            "ault", Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetBCSInvalidParameterExcepti" +
            "onFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetBCSUnconfiguredWebServiceE" +
            "xceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        System.IO.Stream GetBCS(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetFileref", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetFilerefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidDeviceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetFilerefInvalidDeviceExcept" +
            "ionFault", Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetFilerefInvalidParameterExc" +
            "eptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetFilerefUnconfiguredWebServ" +
            "iceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        System.IO.Stream GetFileref(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetPeripheralDegrees", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetPeripheralDegreesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetPeripheralDegreesInvalidPa" +
            "rameterExceptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidDeviceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetPeripheralDegreesInvalidDe" +
            "viceExceptionFault", Name="InvalidDeviceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetPeripheralDegreesUnconfigu" +
            "redWebServiceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        Wineyes.Search.PeripheralDegreesModule GetPeripheralDegrees(string ImageId, bool Anterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetImage", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetImageUnconfiguredWebServic" +
            "eExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetImageInvalidParameterExcep" +
            "tionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        System.IO.Stream GetImage(string ImageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetDerived", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetDerivedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetDerivedInvalidParameterExc" +
            "eptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetDerivedUnconfiguredWebServ" +
            "iceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        System.IO.Stream GetDerived(string ImageId, string Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetReport", ReplyAction="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.InvalidParameterException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetReportInvalidParameterExce" +
            "ptionFault", Name="InvalidParameterException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wineyes.Search.UnconfiguredWebServiceException), Action="urn:schemas-csoitalia-it:psearchsvc-v10/IPSearchSvc/GetReportUnconfiguredWebServi" +
            "ceExceptionFault", Name="UnconfiguredWebServiceException", Namespace="urn:schemas-csoitalia-it:phoenix-dt-v10")]
        System.IO.Stream GetReport(string ReportId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPSearchSvcChannel : Wineyes.Search.IPSearchSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PSearchSvcClient : System.ServiceModel.ClientBase<Wineyes.Search.IPSearchSvc>, Wineyes.Search.IPSearchSvc {
        
        public PSearchSvcClient() {
        }
        
        public PSearchSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSearchSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSearchSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSearchSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wineyes.Search.Patient[] FindPatients(int Maximum, int Page) {
            return base.Channel.FindPatients(Maximum, Page);
        }
        
        public Wineyes.Search.Patient[] SearchPatients(string FirstName, string LastName) {
            return base.Channel.SearchPatients(FirstName, LastName);
        }
        
        public Wineyes.Search.Patient FindPatient(string PatientId, string IdIssuer) {
            return base.Channel.FindPatient(PatientId, IdIssuer);
        }
        
        public Wineyes.Search.Study[] FindStudies(string PatientId) {
            return base.Channel.FindStudies(PatientId);
        }
        
        public Wineyes.Search.Study[] SearchStudies(int Maximum, int Page) {
            return base.Channel.SearchStudies(Maximum, Page);
        }
        
        public Wineyes.Search.Study[] SearchStudiesByDate(System.Nullable<System.DateTime> From, System.Nullable<System.DateTime> To, string Device) {
            return base.Channel.SearchStudiesByDate(From, To, Device);
        }
        
        public Wineyes.Search.Study FindStudy(string StudyId) {
            return base.Channel.FindStudy(StudyId);
        }
        
        public Wineyes.Search.Study FindStudyByAccessionNumber(string AccessionNumber) {
            return base.Channel.FindStudyByAccessionNumber(AccessionNumber);
        }
        
        public Wineyes.Search.Image[] FindImages(string StudyId, string Laterality) {
            return base.Channel.FindImages(StudyId, Laterality);
        }
        
        public System.Drawing.Bitmap GetThumbnail(string Root) {
            return base.Channel.GetThumbnail(Root);
        }
        
        public System.IO.Stream GetThumb(string ImageId) {
            return base.Channel.GetThumb(ImageId);
        }
        
        public Wineyes.Search.Refraction[] FindRefractions(string StudyId, string Laterality) {
            return base.Channel.FindRefractions(StudyId, Laterality);
        }
        
        public Wineyes.Search.Report[] SearchReports(string StudyId, string Title) {
            return base.Channel.SearchReports(StudyId, Title);
        }
        
        public Wineyes.Search.Meridian[] FindSimK(string StudyId) {
            return base.Channel.FindSimK(StudyId);
        }
        
        public Wineyes.Search.Meridian GetSimK(string ImageId) {
            return base.Channel.GetSimK(ImageId);
        }
        
        public int GetAngle(string ImageId) {
            return base.Channel.GetAngle(ImageId);
        }
        
        public System.IO.Stream GetBCS(string ImageId) {
            return base.Channel.GetBCS(ImageId);
        }
        
        public System.IO.Stream GetFileref(string ImageId) {
            return base.Channel.GetFileref(ImageId);
        }
        
        public Wineyes.Search.PeripheralDegreesModule GetPeripheralDegrees(string ImageId, bool Anterior) {
            return base.Channel.GetPeripheralDegrees(ImageId, Anterior);
        }
        
        public System.IO.Stream GetImage(string ImageId) {
            return base.Channel.GetImage(ImageId);
        }
        
        public System.IO.Stream GetDerived(string ImageId, string Info) {
            return base.Channel.GetDerived(ImageId, Info);
        }
        
        public System.IO.Stream GetReport(string ReportId) {
            return base.Channel.GetReport(ReportId);
        }
    }
}
